# Generated by Django 6.0.8 on 2026-08-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='telegram',
            field=models.URLField(blank=True),
        ),
    ]
