# Generated by Django 6.0.8 on 2026-09-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationrequest',
            name='preferred_day',
            field=models.CharField(blank=True, choices=[('saturday', 'شنبه'), ('sunday', 'یکشنبه'), ('monday', 'دوشنبه'), ('tuesday', 'سه\u200cشنبه'), ('wednesday', 'چهارشنبه'), ('thursday', 'پنجشنبه')], max_length=10),
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='preferred_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
