# Generated by Django 6.0.8 on 2026-09-13 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_registrationrequest_preferred_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationrequest',
            name='preferred_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
