# Generated by Django 6.0.8 on 2026-09-15 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0004_alter_registrationrequest_preferred_day'),
        ('schedules', '0006_classsession_enrollment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationrequest',
            name='enrollment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_request', to='schedules.enrollment'),
        ),
    ]
