# Generated by Django 6.0.8 on 2026-09-09 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('saturday', 'شنبه'), ('sunday', 'یکشنبه'), ('monday', 'دوشنبه'), ('tuesday', 'سه\u200cشنبه'), ('wednesday', 'چهارشنبه'), ('thursday', 'پنجشنبه')], db_index=True, max_length=10)),
                ('start_time', models.TimeField(db_index=True)),
                ('student_name', models.CharField(max_length=150)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('instrument', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['day', 'start_time'],
                'constraints': [models.UniqueConstraint(fields=('day', 'start_time'), name='unique_class_booking_slot')],
            },
        ),
    ]
