# Generated by Django 6.0.8 on 2026-09-09 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
        ('students', '0002_alter_student_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='classbooking',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_bookings', to='students.student'),
        ),
    ]
