# Generated by Django 6.0.8 on 2026-09-13 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_classbooking_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilityException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date', 'start_time'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('start_time__isnull', True), ('end_time__isnull', True)), models.Q(('start_time__isnull', False), ('end_time__isnull', False), ('start_time__lt', models.F('end_time'))), _connector='OR'), name='availability_exception_valid_time_range'), models.UniqueConstraint(condition=models.Q(('start_time__isnull', True), ('end_time__isnull', True)), fields=('date',), name='unique_full_day_availability_exception'), models.UniqueConstraint(condition=models.Q(('start_time__isnull', False), ('end_time__isnull', False)), fields=('date', 'start_time', 'end_time'), name='unique_timed_availability_exception')],
            },
        ),
        migrations.CreateModel(
            name='WeeklyAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('saturday', 'شنبه'), ('sunday', 'یکشنبه'), ('monday', 'دوشنبه'), ('tuesday', 'سه\u200cشنبه'), ('wednesday', 'چهارشنبه'), ('thursday', 'پنجشنبه')], db_index=True, max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['day', 'start_time'],
                'constraints': [models.CheckConstraint(condition=models.Q(('start_time__lt', models.F('end_time'))), name='weekly_availability_start_before_end'), models.UniqueConstraint(fields=('day', 'start_time', 'end_time'), name='unique_weekly_availability_range')],
            },
        ),
    ]
