# Generated by Django 6.0.8 on 2026-09-15 15:08

import django.db.models.deletion
from datetime import timedelta

from django.db import migrations, models
from django.db.models import Q
from django.utils import timezone


PYTHON_WEEKDAYS = {
    "monday": 0,
    "tuesday": 1,
    "wednesday": 2,
    "thursday": 3,
    "friday": 4,
    "saturday": 5,
    "sunday": 6,
}


def get_next_date(
    booking,
    current_date_time,
):
    days_until_class = (
        PYTHON_WEEKDAYS[booking.day]
        - current_date_time.date().weekday()
    ) % 7

    current_time = (
        current_date_time.time()
        .replace(tzinfo=None)
    )

    if (
        days_until_class == 0
        and booking.start_time <= current_time
    ):
        days_until_class = 7

    return (
        current_date_time.date()
        + timedelta(days=days_until_class)
    )


def backfill_existing_bookings(
    apps,
    schema_editor,
):
    Student = apps.get_model(
        "students",
        "Student",
    )
    ClassBooking = apps.get_model(
        "schedules",
        "ClassBooking",
    )
    ClassSession = apps.get_model(
        "schedules",
        "ClassSession",
    )
    Enrollment = apps.get_model(
        "schedules",
        "Enrollment",
    )
    AvailabilityException = apps.get_model(
        "schedules",
        "AvailabilityException",
    )

    current_date_time = timezone.localtime()
    bookings_by_student = {}

    for booking in ClassBooking.objects.all():
        student = None

        if booking.student_id:
            student = Student.objects.filter(
                pk=booking.student_id
            ).first()

        if student is None:
            student = Student.objects.filter(
                phone=booking.phone
            ).first()

        if student is None:
            continue

        if booking.student_id != student.id:
            booking.student_id = student.id
            booking.save(
                update_fields=["student"]
            )

        bookings_by_student.setdefault(
            student.id,
            [],
        ).append(booking)

    for student_id, bookings in (
        bookings_by_student.items()
    ):
        starts_on = min(
            get_next_date(
                booking,
                current_date_time,
            )
            for booking in bookings
        )
        expires_on = starts_on + timedelta(
            days=30
        )

        enrollment = Enrollment.objects.create(
            student_id=student_id,
            starts_on=starts_on,
            expires_on=expires_on,
            is_active=True,
        )

        for booking in bookings:
            booking.enrollment_id = enrollment.id
            booking.save(
                update_fields=["enrollment"]
            )

            days_until_first = (
                PYTHON_WEEKDAYS[booking.day]
                - starts_on.weekday()
            ) % 7
            session_date = (
                starts_on
                + timedelta(days=days_until_first)
            )

            while session_date < expires_on:
                exception = (
                    AvailabilityException.objects
                    .filter(date=session_date)
                    .filter(
                        Q(
                            start_time__isnull=True,
                            end_time__isnull=True,
                        )
                        | Q(
                            start_time__lte=(
                                booking.start_time
                            ),
                            end_time__gt=(
                                booking.start_time
                            ),
                        )
                    )
                    .order_by("start_time")
                    .first()
                )

                ClassSession.objects.create(
                    booking_id=booking.id,
                    date=session_date,
                    start_time=booking.start_time,
                    status=(
                        "cancelled"
                        if exception
                        else "scheduled"
                    ),
                    cancellation_reason=(
                        exception.reason
                        if exception
                        else ""
                    ),
                    availability_exception_id=(
                        exception.id
                        if exception
                        else None
                    ),
                )

                session_date += timedelta(days=7)


def remove_backfilled_data(
    apps,
    schema_editor,
):
    ClassBooking = apps.get_model(
        "schedules",
        "ClassBooking",
    )
    ClassSession = apps.get_model(
        "schedules",
        "ClassSession",
    )
    Enrollment = apps.get_model(
        "schedules",
        "Enrollment",
    )

    ClassSession.objects.all().delete()
    ClassBooking.objects.update(
        enrollment=None
    )
    Enrollment.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0005_alter_classbooking_day_alter_weeklyavailability_day'),
        ('students', '0002_alter_student_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('start_time', models.TimeField(db_index=True)),
                ('status', models.CharField(choices=[('scheduled', 'برگزار می\u200cشود'), ('cancelled', 'لغو شده'), ('completed', 'برگزار شده')], db_index=True, default='scheduled', max_length=20)),
                ('cancellation_reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_on', models.DateField(db_index=True)),
                ('expires_on', models.DateField(db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-starts_on', '-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='classbooking',
            name='unique_class_booking_slot',
        ),
        migrations.AddField(
            model_name='classsession',
            name='availability_exception',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_sessions', to='schedules.availabilityexception'),
        ),
        migrations.AddField(
            model_name='classsession',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='schedules.classbooking'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='students.student'),
        ),
        migrations.AddField(
            model_name='classbooking',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weekly_bookings', to='schedules.enrollment'),
        ),
        migrations.AddConstraint(
            model_name='classsession',
            constraint=models.UniqueConstraint(fields=('date', 'start_time'), name='unique_class_session_slot'),
        ),
        migrations.AddConstraint(
            model_name='classsession',
            constraint=models.UniqueConstraint(fields=('booking', 'date'), name='unique_booking_session_date'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.CheckConstraint(condition=models.Q(('starts_on__lt', models.F('expires_on'))), name='enrollment_starts_before_expiration'),
        ),
        migrations.RunPython(
            backfill_existing_bookings,
            remove_backfilled_data,
        ),
    ]
